<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedKernel\ExamPlatform.SharedKernel.Application\ExamPlatform.SharedKernel.Application.csproj" />
    <ProjectReference Include="..\ExamPlatform.Modules.Batch.Application\ExamPlatform.Modules.Batch.Application.csproj" />
    <ProjectReference Include="..\ExamPlatform.Modules.Batch.Infrastructure\ExamPlatform.Modules.Batch.Infrastructure.csproj" />
  </ItemGroup>
</Project>
