<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ExamPlatform.Modules.Analytics.Domain\ExamPlatform.Modules.Analytics.Domain.csproj" />
    <ProjectReference Include="..\ExamPlatform.Modules.Analytics.Contracts\ExamPlatform.Modules.Analytics.Contracts.csproj" />
    <ProjectReference Include="..\..\ExamRuntime\ExamPlatform.Modules.ExamRuntime.Contracts\ExamPlatform.Modules.ExamRuntime.Contracts.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\ExamPlatform.SharedKernel.Application\ExamPlatform.SharedKernel.Application.csproj" />
  </ItemGroup>
</Project>
