// <auto-generated />
using System;
using ExamPlatform.Modules.Proctoring.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamPlatform.Modules.Proctoring.Infrastructure.Migrations
{
    [DbContext(typeof(ProctoringDbContext))]
    [Migration("20261010043549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("proctoring")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamPlatform.Modules.Proctoring.Domain.RiskAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.HasIndex("ExamId", "Status");

                    b.ToTable("RiskAssessments", "proctoring");
                });

            modelBuilder.Entity("ExamPlatform.Modules.Proctoring.Domain.RiskAssessment", b =>
                {
                    b.OwnsMany("ExamPlatform.Modules.Proctoring.Domain.RiskSignalReading", "Signals", b1 =>
                        {
                            b1.Property<Guid>("RiskAssessmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<int>("Points")
                                .HasColumnType("integer");

                            b1.Property<bool>("Raised")
                                .HasColumnType("boolean");

                            b1.Property<string>("RaisedWhen")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<decimal>("Threshold")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)");

                            b1.Property<decimal?>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer");

                            b1.HasKey("RiskAssessmentId", "Kind");

                            b1.ToTable("RiskSignalReadings", "proctoring");

                            b1.WithOwner()
                                .HasForeignKey("RiskAssessmentId");
                        });

                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
