// <auto-generated />
using System;
using ExamPlatform.Modules.ExamAuthoring.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamPlatform.Modules.ExamAuthoring.Infrastructure.Migrations
{
    [DbContext(typeof(ExamAuthoringDbContext))]
    [Migration("20261010054830_InstructionTemplates")]
    partial class InstructionTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LateEntryDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ScheduledEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Exams", "examAuthoring");
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("SectionId");

                    b.ToTable("ExamQuestions", "examAuthoring");
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.ExamSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamSections", "examAuthoring");
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.InstructionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InstructionTemplates", "examAuthoring");
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.SectionDrawRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Topic")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionDrawRules", "examAuthoring");
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.Exam", b =>
                {
                    b.OwnsOne("ExamPlatform.Modules.ExamAuthoring.Domain.ExamConfig", "Config", b1 =>
                        {
                            b1.Property<Guid>("ExamId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("CalculatorAllowed")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ContentProtection")
                                .HasColumnType("boolean");

                            b1.Property<int>("FocusViolationLimit")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxAttempts")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxRetakes")
                                .HasColumnType("integer");

                            b1.Property<string>("ResultReleaseMode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ResultReleaseTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("ScratchpadAllowed")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SectionLockEnabled")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ShuffleOptions")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ShuffleQuestions")
                                .HasColumnType("boolean");

                            b1.Property<int?>("TotalTimeSeconds")
                                .HasColumnType("integer");

                            b1.HasKey("ExamId");

                            b1.ToTable("Exams", "examAuthoring");

                            b1.WithOwner()
                                .HasForeignKey("ExamId");

                            b1.OwnsOne("ExamPlatform.Modules.ExamAuthoring.Domain.MarkingScheme", "MarkingScheme", b2 =>
                                {
                                    b2.Property<Guid>("ExamConfigExamId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("CorrectMarks")
                                        .HasColumnType("numeric");

                                    b2.Property<decimal>("IncorrectMarks")
                                        .HasColumnType("numeric");

                                    b2.Property<bool>("PartialCredit")
                                        .HasColumnType("boolean");

                                    b2.Property<decimal>("UnattemptedMarks")
                                        .HasColumnType("numeric");

                                    b2.HasKey("ExamConfigExamId");

                                    b2.ToTable("Exams", "examAuthoring");

                                    b2.WithOwner()
                                        .HasForeignKey("ExamConfigExamId");
                                });

                            b1.Navigation("MarkingScheme")
                                .IsRequired();
                        });

                    b.OwnsOne("ExamPlatform.Modules.ExamAuthoring.Domain.ExamScope", "Scope", b1 =>
                        {
                            b1.Property<Guid>("ExamId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("BookId")
                                .HasColumnType("uuid")
                                .HasColumnName("ScopeBookId");

                            b1.PrimitiveCollection<Guid[]>("ChapterIds")
                                .IsRequired()
                                .HasColumnType("uuid[]")
                                .HasColumnName("ScopeChapterIds");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ScopeType");

                            b1.HasKey("ExamId");

                            b1.ToTable("Exams", "examAuthoring");

                            b1.WithOwner()
                                .HasForeignKey("ExamId");
                        });

                    b.Navigation("Config")
                        .IsRequired();

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.ExamQuestion", b =>
                {
                    b.HasOne("ExamPlatform.Modules.ExamAuthoring.Domain.ExamSection", null)
                        .WithMany("Questions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.ExamSection", b =>
                {
                    b.HasOne("ExamPlatform.Modules.ExamAuthoring.Domain.Exam", null)
                        .WithMany("Sections")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.SectionDrawRule", b =>
                {
                    b.HasOne("ExamPlatform.Modules.ExamAuthoring.Domain.ExamSection", null)
                        .WithMany("DrawRules")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.Exam", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ExamPlatform.Modules.ExamAuthoring.Domain.ExamSection", b =>
                {
                    b.Navigation("DrawRules");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
