<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Analytics\ExamPlatform.Modules.Analytics.Domain\ExamPlatform.Modules.Analytics.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\Analytics\ExamPlatform.Modules.Analytics.Contracts\ExamPlatform.Modules.Analytics.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\Analytics\ExamPlatform.Modules.Analytics.Application\ExamPlatform.Modules.Analytics.Application.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\ExamRuntime\ExamPlatform.Modules.ExamRuntime.Contracts\ExamPlatform.Modules.ExamRuntime.Contracts.csproj" />
  </ItemGroup>

</Project>
