<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\QuestionBank\ExamPlatform.Modules.QuestionBank.Domain\ExamPlatform.Modules.QuestionBank.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\QuestionBank\ExamPlatform.Modules.QuestionBank.Application\ExamPlatform.Modules.QuestionBank.Application.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\QuestionBank\ExamPlatform.Modules.QuestionBank.Contracts\ExamPlatform.Modules.QuestionBank.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\QuestionBank\ExamPlatform.Modules.QuestionBank.Infrastructure\ExamPlatform.Modules.QuestionBank.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\src\SharedKernel\ExamPlatform.SharedKernel.Application\ExamPlatform.SharedKernel.Application.csproj" />
  </ItemGroup>

</Project>
