<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ExamPlatform.Modules.Admin.Domain\ExamPlatform.Modules.Admin.Domain.csproj" />
    <ProjectReference Include="..\ExamPlatform.Modules.Admin.Contracts\ExamPlatform.Modules.Admin.Contracts.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\ExamPlatform.SharedKernel.Application\ExamPlatform.SharedKernel.Application.csproj" />
  </ItemGroup>
</Project>
