<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedKernel\ExamPlatform.SharedKernel.Application\ExamPlatform.SharedKernel.Application.csproj" />
    <ProjectReference Include="..\ExamPlatform.Modules.QuestionBank.Application\ExamPlatform.Modules.QuestionBank.Application.csproj" />
    <ProjectReference Include="..\ExamPlatform.Modules.QuestionBank.Infrastructure\ExamPlatform.Modules.QuestionBank.Infrastructure.csproj" />
    <ProjectReference Include="..\ExamPlatform.Modules.QuestionBank.Contracts\ExamPlatform.Modules.QuestionBank.Contracts.csproj" />
  </ItemGroup>
</Project>
