<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExamPlatform.Modules.Consent.Application\ExamPlatform.Modules.Consent.Application.csproj" />
    <ProjectReference Include="..\ExamPlatform.Modules.Consent.Infrastructure\ExamPlatform.Modules.Consent.Infrastructure.csproj" />
  </ItemGroup>
</Project>
